// Mock data for GitHub Pages static deployment
const mockTweet1 = {
  id: '1',
  author: { id: 'Misaka', name: 'Misaka Mikoto', profile_photo: '/images/img.png' },
  text: '楽しかった！！！！\nアンヴィル…………',
  images: ['/images/92162034_p3.png'],
  publishTime: '2026-06-04T02:00:00',
  interaction: { reply: 2, transpond: 333, upvote: 444, view: 999, bookmark: 10 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockTweet2 = {
  id: '2',
  author: { id: 'oO0Eve0Oo', name: 'Eve', profile_photo: '/images/img.png' },
  text: '今日もいい天気ですね〜',
  images: ['/images/93447255_p0.png'],
  publishTime: '2026-06-05T10:00:00',
  interaction: { reply: 55, transpond: 120, upvote: 310, view: 500, bookmark: 20 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockTweet3 = {
  id: '3',
  author: { id: 'akakura1341', name: '赤倉🧸', profile_photo: '/images/img.png' },
  text: '新しいプロジェクトを始めました！\nVue.js + TypeScript で Twitter クローンを作っています。',
  images: ['/images/92162034_p3.png', '/images/96919363_p0.jpg', '/images/93447255_p0.png'],
  publishTime: '2026-06-03T15:00:00',
  interaction: { reply: 88, transpond: 200, upvote: 500, view: 1200, bookmark: 50 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockReply1 = {
  id: '4',
  author: { id: 'Misaka', name: 'Misaka Mikoto', profile_photo: '/images/img.png' },
  text: '这条推文太棒了！👍',
  images: [],
  publishTime: '2026-06-05T16:27:29',
  interaction: { reply: 0, transpond: 0, upvote: 0, view: 0, bookmark: 0 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockReply2 = {
  id: '5',
  author: { id: 'oO0Eve0Oo', name: 'Eve', profile_photo: '/images/img.png' },
  text: 'hhh',
  images: [],
  publishTime: '2026-06-05T10:17:17',
  interaction: { reply: 0, transpond: 0, upvote: 0, view: 0, bookmark: 0 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockTweet4 = {
  id: '8',
  author: { id: 'Misaka', name: 'Misaka Mikoto', profile_photo: '/images/img.png' },
  text: '多图片测试 - 2张',
  images: ['/images/92162034_p3.png', '/images/96919363_p0.jpg'],
  publishTime: '2026-06-14T01:00:00',
  interaction: { reply: 0, transpond: 0, upvote: 12, view: 100, bookmark: 0 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockTweet5 = {
  id: '9',
  author: { id: 'Misaka', name: 'Misaka Mikoto', profile_photo: '/images/img.png' },
  text: '多图片测试 - 3张',
  images: ['/images/92162034_p3.png', '/images/96919363_p0.jpg', '/images/93447255_p0.png'],
  publishTime: '2026-06-14T01:00:00',
  interaction: { reply: 0, transpond: 0, upvote: 8, view: 80, bookmark: 0 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockTweet6 = {
  id: '10',
  author: { id: 'Misaka', name: 'Misaka Mikoto', profile_photo: '/images/img.png' },
  text: '多图片测试 - 4张',
  images: ['/images/92162034_p3.png', '/images/96919363_p0.jpg', '/images/93447255_p0.png', '/images/64495434_p0.jpg'],
  publishTime: '2026-06-14T01:00:00',
  interaction: { reply: 0, transpond: 0, upvote: 5, view: 60, bookmark: 0 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockTweet7 = {
  id: '11',
  author: { id: 'Misaka', name: 'Misaka Mikoto', profile_photo: '/images/img.png' },
  text: '多图片测试 - 9张',
  images: ['/images/92162034_p3.png', '/images/96919363_p0.jpg', '/images/93447255_p0.png', '/images/64495434_p0.jpg', '/images/92162034_p3.png', '/images/96919363_p0.jpg', '/images/93447255_p0.png', '/images/64495434_p0.jpg', '/images/92162034_p3.png'],
  publishTime: '2026-06-14T01:00:00',
  interaction: { reply: 0, transpond: 0, upvote: 3, view: 40, bookmark: 0 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockTweet8 = {
  id: '12',
  author: { id: 'Misaka', name: 'Misaka Mikoto', profile_photo: '/images/img.png' },
  text: '多图片测试 - 5张',
  images: ['/images/92162034_p3.png', '/images/96919363_p0.jpg', '/images/93447255_p0.png', '/images/64495434_p0.jpg', '/images/92162034_p3.png'],
  publishTime: '2026-06-14T01:00:00',
  interaction: { reply: 0, transpond: 0, upvote: 2, view: 30, bookmark: 0 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}
const mockTweet9 = {
  id: '13',
  author: { id: 'Misaka', name: 'Misaka Mikoto', profile_photo: '/images/img.png' },
  text: '多图片测试 - 6张',
  images: ['/images/92162034_p3.png', '/images/96919363_p0.jpg', '/images/93447255_p0.png', '/images/64495434_p0.jpg', '/images/92162034_p3.png', '/images/96919363_p0.jpg'],
  publishTime: '2026-06-14T01:00:00',
  interaction: { reply: 0, transpond: 0, upvote: 1, view: 20, bookmark: 0 },
  myUpvote: false, myTranspond: false, myBookmark: false,
}

export const mockResponses = {
  'GET /tweet': [mockTweet1, mockTweet2, mockTweet3, mockReply1, mockReply2, mockTweet4, mockTweet5, mockTweet6, mockTweet7, mockTweet8, mockTweet9],
  'GET /tweet/1': { ...mockTweet1, replyTo: null },
  'GET /tweet/2': { ...mockTweet2, replyTo: null },
  'GET /tweet/3': { ...mockTweet3, replyTo: null },
  'GET /tweet/4': { ...mockReply1, replyTo: mockTweet1 },
  'GET /tweet/5': { ...mockReply2, replyTo: mockTweet1 },
  'GET /tweet/8': { ...mockTweet4, replyTo: null },
  'GET /tweet/9': { ...mockTweet5, replyTo: null },
  'GET /tweet/10': { ...mockTweet6, replyTo: null },
  'GET /tweet/11': { ...mockTweet7, replyTo: null },
  'GET /tweet/12': { ...mockTweet8, replyTo: null },
  'GET /tweet/13': { ...mockTweet9, replyTo: null },
  'GET /tweet/1/replies': [mockReply1, mockReply2],
  'GET /tweet/2/replies': [],
  'GET /tweet/3/replies': [],
  'POST /tweet/1/reply': { status: 'success', id: '6' },
  'POST /tweet/1/upvote': { status: 'success', active: true, count: 445 },
  'POST /tweet/1/transpond': { status: 'success', active: true, count: 334 },
  'POST /tweet/1/bookmark': { status: 'success', active: true, count: 11 },
  'POST /tweet/2/upvote': { status: 'success', active: true, count: 311 },
  'POST /tweet/2/transpond': { status: 'success', active: true, count: 121 },
  'POST /tweet/2/bookmark': { status: 'success', active: true, count: 21 },
  'POST /tweet/3/upvote': { status: 'success', active: true, count: 501 },
  'POST /tweet/3/transpond': { status: 'success', active: true, count: 201 },
  'POST /tweet/3/bookmark': { status: 'success', active: true, count: 51 },
  'GET /trends': [
    { category: '中国香港特别行政区', topic: 'LING NIVEA BRAND FRIEND' },
    { category: '台湾', topic: '#skywongravee' },
    { category: '日本', topic: '#アニメ' },
    { category: '技术', topic: 'Vue.js' },
    { category: '全球', topic: '#OpenSource' },
    { category: '科技', topic: '#TypeScript' },
    { category: '娱乐', topic: '#新番推荐' },
    { category: '游戏', topic: '#原神' },
    { category: '音乐', topic: '#JPop' },
    { category: '体育', topic: '#NBA' },
    { category: '科技', topic: '#AI绘画' },
    { category: '全球', topic: '#ClimateAction' },
    { category: '日本', topic: '#東京リベンジャーズ' },
    { category: '中国台湾', topic: '#金马奖' },
    { category: '技术', topic: 'React vs Vue' },
    { category: '娱乐', topic: '#动漫电影' },
    { category: '游戏', topic: '#塞尔达传说' },
    { category: '科技', topic: '#GitHubCopilot' },
    { category: '全球', topic: '#WorldCup2026' },
    { category: '日本', topic: '#呪術廻戦' },
  ],
  'GET /currentUser': { username: 'Misaka 10177', userId: 'Misaka10177' },
  'POST /checkUser': { status: 'success' },
  'POST /login': { status: 'success', accessToken: 'mock-token-gh-pages' },
  'POST /refresh': { accessToken: 'mock-token-gh-pages' },
  'POST /logout': { status: 'success' },
}
